remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Hi there, I'm Leonardo Pereira.
description: I'm a seasoned writer from SÃ£o Paulo ðŸ‡§ðŸ‡·, currently based in Dublin ðŸ‡®ðŸ‡ª for the past nine years.

With over a decade of experience in content creation and web design, I hold a BA in Journalism and have pursued further studies in Technical Writing and Digital Marketing.

My diverse portfolio includes translation and localisation projects, style guides, reports, case studies and various types of web content. This encompasses infographics, news articles, blogs, email templates, video and podcast scripts and social media posts.
